# Generated by Django 6.0.3 on 2026-04-06 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether the 2-hour reminder email has been sent'),
        ),
        migrations.CreateModel(
            name='TieBreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiebreaker_decisions', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiebreakers', to='voting.election')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiebreakers', to='voting.position')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiebreaker_wins', to='voting.candidate')),
            ],
            options={
                'unique_together': {('election', 'position')},
            },
        ),
        migrations.CreateModel(
            name='VoteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('experience', models.CharField(choices=[('smooth', 'Very Smooth'), ('neutral', 'Neutral'), ('problematic', 'Had Issues')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='voting.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('voter', 'election')},
            },
        ),
    ]
